---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    users:
      - name: tom
        groups:
          - people
          - bofh
        password: 12345
        keys:
          - mykey1
          - mykey2
      - name: bob
        password: 67890
        keys:
          - bobkey0
          - bobkey1
        groups:
          - biff
          - boff
      - name: jon
        password: abcdef
        keys:
          - jonkey
          - dnokey
        groups:
          - jiff
          - jaff
    userlist:
      - tom
      - jon

  tasks:
    - debug:
        msg: "{{ users | selectattr('name', 'equalto', 'tom') | list }}"

    - debug:
        msg: "{{ users | selectattr('name', 'equalto', item) | list }}"
      with_items: "{{ userlist }}"

    - debug:
        msg: "{{ users | selectattr('name', 'equalto', item) | map(attribute='keys') | list }}"
      with_items: "{{ userlist }}"
