---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    users:
      tom:
        groups:
          - people
          - bofh
        password: 12345
        keys:
          - mykey1
          - mykey2
      bob:
        password: 67890
        keys:
          - bobkey0
          - bobkey1
        groups:
          - biff
          - boff
      jon:
        password: abcdef
        keys:
          - jonkey
          - dnokey
        groups:
          - jiff
          - jaff
    userlist:
      - tom
      - jon

  tasks:
    - debug:
        msg: "{{ userlist | map('extract', users) | list }}"

    - debug:
        msg: "{{ userlist | map('extract', users) | map(attribute='keys') | list }}"

    - debug:
        var: item
      with_together:
        - "{{ userlist }}"
        - "{{ userlist | map('extract', users) | list }}"

    - debug:
        var: item
      with_together:
        - "{{ userlist }}"
        - "{{ userlist | map('extract', users) | map(attribute='keys') | list }}"


