---
- hosts: localhost
  gather_facts: no
  vars:
    asg_properties: {DesiredCapacity: 11}
    desired_capacity: 9
    min_size: 20
  tasks:
    - debug:
        msg: "{{ [min_size, asg_properties.DesiredCapacity | default(desired_capacity)] | max }}"
    - debug:
        msg: "{{ [min_size, asg_properties.DesiredCapacity | default(desired_capacity) / 2] | max }}"
    - debug:
        msg: "{{ [min_size, (asg_properties.DesiredCapacity | default(desired_capacity) / 2)] | max | round(0, 'ceil') }}"
    - debug:
        msg: "{{ [min_size, (asg_properties.DesiredCapacity | default(desired_capacity) / 2)] | max | round(0, 'ceil') | int }}"
