---

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    thedict:
      blah: bloi
      blush: blop

  tasks:
  
    - debug:
        msg: blah
      when: "'blah' in thedict"

# vim: set ts=2 sts=2 sw=2 et:
