---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    mystr: blah.domain.net

  tasks:

    - debug:
        msg: "{{ mystr.split('.')[0] }}"

# vim: set ft=ansible ts=2 sts=2 sw=2 et:
